# Generated by Django 5.2.3 on 2025-06-24 18:14

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagesection",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
