# Generated by Django 5.2.3 on 2025-06-22 20:29

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0007_alter_pagesection_content_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagesection",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
