# Generated by Django 5.2.3 on 2025-06-22 20:48

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0008_alter_pagesection_content_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
