# Generated by Django 5.2.3 on 2025-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "profile"},
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
