# Generated by Django 5.2.3 on 2025-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rakau", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contextroot",
            name="sites",
            field=models.ManyToManyField(
                through="rakau.SiteContext",
                through_fields=("context_root", "site"),
                to="sites.site",
            ),
        ),
    ]
