# Generated by Django 5.2.3 on 2025-08-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_remove_resume_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="skills",
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(blank=True, to="resume.skill"),
        ),
        migrations.AlterField(
            model_name="job",
            name="certifications",
            field=models.ManyToManyField(blank=True, to="resume.certification"),
        ),
        migrations.AlterField(
            model_name="job",
            name="education",
            field=models.ManyToManyField(blank=True, to="resume.education"),
        ),
    ]
