# Generated by Django 5.2.3 on 2025-08-25 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_remove_job_skills_resume_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resume.organization"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="resume.resume",
            ),
        ),
    ]
