# Generated by Django 5.2.3 on 2025-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_job_company_alter_job_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="job",
            name="education",
        ),
        migrations.AddField(
            model_name="resume",
            name="certifications",
            field=models.ManyToManyField(blank=True, to="resume.certification"),
        ),
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.ManyToManyField(blank=True, to="resume.education"),
        ),
    ]
