# Generated by Django 5.2.3 on 2025-08-27 00:42

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_alter_resume_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-end_date"]},
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="resume/companies/"
            ),
        ),
    ]
