# Generated by Django 5.2.3 on 2025-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_alter_job_options_alter_job_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certification",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
