# Generated by Django 5.2.3 on 2025-08-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_alter_certification_options_alter_education_degree_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-end_date"]},
        ),
    ]
