# Generated by Django 5.2.3 on 2025-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0010_alter_education_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
