# Generated by Django 5.1 on 2025-03-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awa", "0006_alter_sitelink_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitelink",
            name="email",
            field=models.EmailField(blank=True, max_length=128),
        ),
    ]
