# Generated by Django 5.2.3 on 2025-06-25 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0002_alter_pagesection_content_alter_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tuhi.pagesection",
                    ),
                ),
            ],
        ),
    ]
